version: '3.3'
services:
  nexus:
    build: .
    image: ragedunicorn/nexus:1.0.0-stable
    ports:
      - "8080:8080"
    labels:
      com.ragedunicorn.nexus.environment: "prod"
      com.ragedunicorn.nexus.description: "Sonatype Nexus"
