version: '3.6'
services:
  nexus:
    image: ragedunicorn/nexus:1.0.2-stable
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.nexus.environment: "prod"
      com.ragedunicorn.nexus.description: "Sonatype Nexus"
volumes:
  nexus_data: {}
