version: '3.7'
services:
  nexus:
    build: .
    image: ragedunicorn/nexus:${NEXUS_TAG_VERSION}-dev
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.nexus.environment: "dev"
      com.ragedunicorn.nexus.description: "Sonatype Nexus"
volumes:
  nexus_data: {}
