version: '3.4'
services:
  nexus:
    image: ragedunicorn/nexus:1.0.2-stable
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.nexus.environment: "prod"
      com.ragedunicorn.nexus.description: "Sonatype Nexus"
volumes:
  nexus_data: {}
