version: '3.3'
services:
  nexus:
    build: .
    image: ragedunicorn/nexus:1.0.1-dev
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.nexus.environment: "dev"
      com.ragedunicorn.nexus.description: "Sonatype Nexus"
volumes:
  nexus_data: {}
